// components/Footer.tsx
import Image from "next/image";
import { site } from "@/lib/site";
import ContactForm from "./ContactForm";
import Heading from "./Heading";
import SocialLinks from "./SocialLinks";
import sky from "@/public/images/sky.png";

export default function Footer() {
  return (
    <footer id="contact" className="relative mt-20 scroll-mt-8 print:hidden">
      <Image className="absolute bottom-0 -z-1 dark:hidden" src={sky} alt="" sizes="100vw" />

      <div className="site-container sm:px-20">
        <Heading caption="Contact" className="items-center">
          Get in touch
        </Heading>

        <p className="mb-6 text-center text-muted">
          Email me at{" "}
          <a href={`mailto:${site.email}`} className="text-accent underline-offset-2 hover:underline">
            {site.email}
          </a>{" "}
          or send a message below.
        </p>

        <ContactForm />

        <div className="flex flex-col items-center gap-2 border-t py-6 sm:flex-row sm:justify-between">
          <p className="text-2xs text-muted">
            &copy; {new Date().getFullYear()} {site.name}
          </p>
          <SocialLinks className="-mr-2" />
        </div>
      </div>
    </footer>
  );
}

// src/components/organisms/footer/index.vue
<template>
  <footer class="relative mt-20">
    <g-image class="absolute bottom-0 -z-1" src="~/images/sky.png" alt="sky" />

    <div class="container sm:px-20">
      <g-heading caption="Contact" class="items-center">
        Get in touch
      </g-heading>

      <form
        name="contact"
        class="grid grid-cols-1 gap-4 mb-10 sm:grid-cols-2"
        method="POST"
        data-netlify
        data-netlify-recaptcha
        data-netlify-honeypot="bot-field"
      >
        <input type="hidden" name="form-name" value="contact" />

        <div class="">
          <label
            for="name"
            class="block mb-1 font-medium tracking-wide cursor-pointer"
          >
            Full name
          </label>
          <input
            id="name"
            class="block w-full h-10 px-4 leading-tight text-gray-700 transition-colors duration-200 border appearance-none focus:outline-none focus:border-secondary-200"
            type="text"
            placeholder="John Doe"
          />
        </div>

        <div class="">
          <label
            for="email"
            class="block mb-1 font-medium tracking-wide cursor-pointer"
          >
            Email address
          </label>

          <input
            id="email"
            class="block w-full h-10 px-4 leading-tight text-gray-700 transition-colors duration-200 border appearance-none focus:outline-none focus:border-secondary-200"
            type="email"
            name="email"
            placeholder="john.doe@mail.com"
          />
        </div>

        <div class="sm:col-span-2">
          <label
            for="message"
            class="block mb-1 font-medium tracking-wide cursor-pointer"
          >
            Message
          </label>

          <textarea
            id="message"
            class="block w-full h-20 px-4 py-3 leading-tight text-gray-700 transition-colors duration-200 border appearance-none focus:outline-none focus:border-secondary-200"
            name="message"
            placeholder="Your message"
          />
        </div>

        <div class="flex justify-end sm:col-span-2">
          <button
            type="submit"
            class="inline-flex items-center h-8 px-6 font-medium text-gray-800 transition-colors duration-200 bg-white border hover:bg-secondary-100 hover:border-secondary-200"
          >
            <span class="mr-2">Send</span>
            <g-icon name="send" />
          </button>
        </div>
      </form>
    </div>
  </footer>
</template>
