// src/components/molecules/articles/index.vue
<template>
  <section>
    <div class="container">
      <g-heading caption="Articles">Mostly talking about CSS</g-heading>

      <ul class="grid gap-6">
        <li v-for="{ node } in articles.edges" :key="node.id">
          <g-article :article="node" />
        </li>
      </ul>
    </div>
  </section>
</template>


<script>
import GArticle from "./article";

export default {
  components: { GArticle },
  props: {
    articles: Object
  }
};
</script>

// components/Articles.tsx
import type { ReactNode } from "react";
import type { Post } from "@/lib/posts";
import ArticleCard from "./ArticleCard";
import Heading from "./Heading";

export default function Articles({ posts, footer }: { posts: Post[]; footer?: ReactNode }) {
  return (
    <section>
      <div className="site-container">
        <Heading caption="Articles">Mostly talking about CSS</Heading>

        <ul className="grid gap-10">
          {posts.map((post) => (
            <li key={post.slug}>
              <ArticleCard post={post} />
            </li>
          ))}
        </ul>

        {footer}
      </div>
    </section>
  );
}
