// components/Pens.tsx
import Image from "next/image";
import type { Pen } from "@/lib/pens";
import Heading from "./Heading";

export default function Pens({ pens }: { pens: Pen[] }) {
  if (pens.length === 0) return null;

  return (
    <section className="bg-black py-10">
      <div className="site-container">
        <Heading className="mb-6" caption="Pens" isLight noMargin>
          My picked pens on{" "}
          <a
            className="hover:underline"
            href="https://codepen.io/bourhaouta"
            target="_blank"
            rel="noopener noreferrer"
          >
            CodePen
          </a>
        </Heading>

        <ul className="grid grid-cols-3 gap-6">
          {pens.map((pen) => (
            <li key={pen.id} className="relative">
              <div className="absolute inset-0 mt-3 ml-3 -mr-2 rounded-lg bg-gray-100/25" />

              <a href={pen.link} title={pen.title} className="ratio" target="_blank" rel="noopener noreferrer">
                <Image
                  className="rounded bg-gray-100"
                  src={`${pen.link}/image/large.png`}
                  alt={pen.title}
                  fill
                  sizes="200px"
                />
              </a>

              <h3 className="my-2 ml-6 truncate font-bold text-white">
                <a href={pen.link} title={pen.title} target="_blank" rel="noopener noreferrer">
                  {pen.title}
                </a>
              </h3>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}

// src/components/molecules/pens/index.vue
<template>
  <section class="py-10 bg-black">
    <div class="container">
      <div>
        <g-heading class="mb-6 " caption="Pens" isLight noMargin>
          My picked pens on
          <a
            class="hover:underline"
            href="https://codepen.io/bourhaouta"
            target="_blank"
            rel="noopener noreferrer"
          >
            CodePen
          </a>
        </g-heading>

        <ul class="grid grid-cols-3 gap-6">
          <li
            v-for="({ node }, index) in pens.edges"
            :key="node.id"
            class="relative"
          >
            <div
              class="absolute inset-0 mt-3 ml-3 -mr-2 bg-gray-100 bg-opacity-25 rounded-lg"
            />

            <g-link :href="node.link" :title="node.title" class="ratio">
              <g-image
                class="bg-gray-100 rounded"
                :src="`${node.link}/image/large.png`"
                :alt="node.title"
              />
            </g-link>

            <h3 class="my-2 ml-6 font-bold text-white truncate">
              <g-link :href="node.link" :title="node.title">
                {{ node.title }}
              </g-link>
            </h3>
          </li>
        </ul>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  props: {
    pens: Object
  }
};
</script>

<style scoped>
</style>
